[package]
name = "CS120-project"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
futures = "*"
hound = "*"
tokio = { version = "*", features = ["full"] }
rodio = "*"
cpal = { version = "*", features = ["asio"] }