[package]
name = "CS120-project"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
futures = "*"
hound = "*"
tokio = { version = "1", features = ["full"] }
rodio = "0.19"
cpal = { version = "*", features = ["asio"] }